#!/usr/bin/env python3
# -*- coding: utf-8 -*-:q

#import os
import argparse
import pathlib

# このプログラムの説明
parser = argparse.ArgumentParser(description='lsコマンドみたいなのを作りました')
# 引数を先に宣言しておく
parser.add_argument('--arg1')  # choices=['all', 'dir', 'file'])
# ファイルやディレクトリの情報を取得
path = pathlib.Path()
# 引数を解析
args = parser.parse_args()

class pycolor:
    BLACK = '\033[30m'
    RED = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE = '\033[34m'
    PURPLE = '\033[35m'
    CYAN = '\033[36m'
    WHITE = '\033[37m'
    RETURN = '\033[07m' #反転
    ACCENT = '\033[01m' #強調
    FLASH = '\033[05m' #点滅
    RED_FLASH = '\033[05;41m' #赤背景+点滅
    END = '\033[0m'

if args.arg1 == 'dir':
    for po in path.iterdir():
        if po.is_dir():
            print(pycolor.BLUE+ str(po) +pycolor.END)
elif args.arg1 == 'file':
    for po in path.iterdir():
        if po.is_file():
            print(pycolor.GREEN+ str(po) +pycolor.END)
elif args.arg1 == 'all' or args.arg1 is None:
    for po in path.iterdir():
        if po.is_file():
            print(pycolor.GREEN+ str(po) +pycolor.END)
        if po.is_dir():
            print(pycolor.BLUE+ str(po) +pycolor.END)
else:
        print (pycolor.RED + 'error' + pycolor.END)



